# This is a basic workflow to help you get started with Actions

name: Automatic Run

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab

jobs:
  # This workflow contains a single job called "build"
  Compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Compilando Java + maven
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 11.0.7
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7

      # Runs a set of commands using the runners shell
      - name: Step 3 - Build Maven
        run: mvn compile

  Test:
    runs-on: ubuntu-latest
    name: Ejecutando tests
    needs: Compile
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 11.0.7
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7

      # Runs a set of commands using the runners shell
      - name: Step 3 - Download Latest Google Chrome
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

      # Runs a set of commands using the runners shell
      - name: Step 4 - Install Google Chrome
        run: sudo apt install ./google-chrome-stable_current_amd64.deb

      # Runs a set of commands using the runners shell
      - name: Step 5 - Run Tests
        run: mvn test -Pheadless
